apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-expoter
  name: redis-exporter
  namespace: prod
spec:
  ports:
  - nodePort:
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    run: redis-export1
  sessionAffinity: None
  type: NodePort




