apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ha
spec:
  version: 7.5.2
  nodeSets:
  - name: zone-a
    count: 1
    config:
      node.attr.zone: europe-west1-a
      cluster.routing.allocation.awareness.attributes: zone
      node.master: true
      node.data: false
      node.ingest: false
#    volumeClaimTemplates:
#    - metadata:
#        name: efs-claim
#      spec:
#        accessModes:
#        - ReadWriteMany
#        resources:
#          requests:
#            storage: 5Gi
#        storageClassName: efs-es

    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: zone-b-data
    count: 1
 #   volumeClaimTemplates:
 #   - metadata:
#        name: efs-claim
#      spec:
#        accessModes:
#        - ReadWriteOnce
#        resources:
#          requests:
#            storage: 5Gi
#        storageClassName: efs-sc

    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
#
