apiVersion: v1
kind: Service
metadata:
  name: k8s-pgmon-grafana
  namespace: mon
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
