---
# the main source :  https://github.com/elastic/helm-charts/tree/master/elasticsearch
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"


# replicas
replicas: 1
minimumMasterNodes: 1
clusterHealthCheckParams: "wait_for_status=yellow"
#  curl -XGET 'localhost:9200/_cluster/health?pretty'  <<<< to check the status

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "200m"
    memory: "500M"
  limits:
    cpu: "200m"
    memory: "500M"

# Service

protocol: http
httpPort: 9200
transportPort: 9300

service:
  labels: {}
  labelsHeadless: {}
  type: NodePort
  nodePort: ""
  annotations: {}
  httpPortName: http
  transportPortName: transport
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: ""

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "topology-aware-standard"
  resources:
    requests:
      storage: 50Gi
