---
# https://github.com/elastic/helm-charts/blob/7.10/kibana/values.yaml
# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "200m"
    memory: "500M"
  limits:
    cpu: "200m"
    memory: "500M"
