apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-pgmon-alertmanager-config
  namespace: mon
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 2m
    route:
      group_by: ['alert']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1m
      receiver: slack
    receivers:
    - name: 'slack'
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#prod-notifications'
        send_resolved: true
        text: |-
            {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                *Description:* {{ .Annotations.description }}
                *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
            {{ end }}
        icon_url: https://avatars3.githubusercontent.com/u/3380462
    templates:
      - '/etc/config/alert/wechat.tmpl'
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
