
# If we should deploy this kubernetes or not.  
# Setting this to false and re-running our deploy playbook will remove the kubernetes deployment 
# example to remove: ansible-playbook kubernetes/kube.deployment.playbook.yml --extra-vars '{deployment_enabled: false}'
deployment_enabled: true
manifest_app_dir: ./templates/
deployment_file: grafana-deploy.yaml
app.name: grafana
service_file: grafana-svc.yaml
configmap_file: grafana-configMapDataSources.yaml
