
# If we should deploy this kubernetes or not.  
# Setting this to false and re-running our deploy playbook will remove the kubernetes deployment 
# example to remove: ansible-playbook kubernetes/kube.deployment.playbook.yml --extra-vars '{deployment_enabled: false}'
deployment_enabled: true
manifest_app_dir: ./templates/
deployment_file: prometheus-deploy.yaml
app.name: prometheus
service_file: prometheus-svc.yaml
rbac_file: prometheus-rbac.yaml
configmap_file: prometheus-configmap.yaml
