- hosts:
    - localhost
  vars_files:
    - ./kube-vars.yml 
  tasks:
    - name: ensure manifest dir exists
      file:
        path: "{{manifest_app_dir}}"
        state: directory

    - name: create manifest template for kube deploy 
      template:
        src: "{{deployment_file}}"
        dest: "{{manifest_app_dir}}/{{deployment_file}}"
      register: deploy_template

    # Apply RBAC
    - block:
        - name: apply kubernetes rbac
          shell: "kubectl apply -f {{manifest_app_dir}}/{{rbac_file}}"
      when: "deployment_enabled"
    # Apply ConfigMap
    - block:
        - name: apply kubernetes configMap
          shell: "kubectl apply -f {{manifest_app_dir}}/{{configmap_file}}"
      when: "deployment_enabled"
    # Apply Deployment
    - block: 
        - name: apply kubernetes deployment
          shell: "kubectl apply -f {{manifest_app_dir}}/{{deployment_file}}"
      when: "deployment_enabled"
    # Apply Service
    - block:
        - name: apply kubernetes service
          shell: "kubectl apply -f {{manifest_app_dir}}/{{service_file}}"
      when: "deployment_enabled"

   # Removals
    - block:
        - name: remove kubernetes rbac
          shell: "kubectl delete -f {{manifest_app_dir}}/{{rbac_file}}"
          register: remove_kube_deployment
      when: not deployment_enabled
    # Removals
    - block:
        - name: remove kubernetes deployment
          shell: "kubectl delete -f {{manifest_app_dir}}/{{deployment_file}}"
          register: remove_kube_deployment
      when: not deployment_enabled
    # Removals
    - block:
        - name: remove kubernetes service
          shell: "kubectl delete -f {{manifest_app_dir}}/{{service_file}}"
          register: remove_kube_deployment
      when: not deployment_enabled
     # Removals
    - block:
        - name: remove kubernetes configmap
          shell: "kubectl delete -f {{manifest_app_dir}}/{{configmap_file}}"
          register: remove_kube_deployment
      when: not deployment_enabled
