apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: mon
spec:
  type: ClusterIP
  ports:
  - name: "wen"
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    k8s-app: node-exporter
