
# If we should deploy this kubernetes or not.  
# Setting this to false and re-running our deploy playbook will remove the kubernetes deployment 
# example to remove: ansible-playbook kubernetes/kube.deployment.playbook.yml --extra-vars '{deployment_enabled: false}'
deployment_enabled: true 
manifest_app_dir: ./templates/
deployment_file: alertmanager-deployment.yaml
app.name: alertmanager 
service_file: alertmanager-service.yaml  
configmap_rules_file: alertmanager-configMapRules.yaml
configmap_alertmanager_file: alertmanager-configMap.yaml
configmap_slack_file: slack-tmplconfigMap.yaml

