---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: k8s-pgmon-prometheus
  namespace: mon
spec:
  type: ClusterIP
  ports:
  - name: "web"
    port: 9090
    protocol: TCP
    targetPort: 9090

  selector:
    app: prometheus
