apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mon
data:
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources:
       - name: Prometheus
         orgId: 1
    datasources:
     - name: Prometheus
       type: prometheus
       access: proxy
       orgId: 1
       url: http://k8s-pgmon-prometheus.mon.svc.cluster.local:9090
       isDefault: true
       version: 1
       editable: false
