apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 7.11.1  # was 7.1.0
  nodeSets:
  - name: master-zone
    count: 3
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
#            resources:
#              limits:
#                memory: 2Gi  

#        initContainers:
#          - name: install-plugins
#            command:
#            - sh
#            - -c
#            - |
#              bin/elasticsearch-plugin install discovery-ec2 

    config:
      node.attr.zone: us-east-1b
      cluster.routing.allocation.awareness.attributes: zone
      node.master: true
      node.data: false
      node.ingest: false

    volumeClaimTemplates:
    - metadata:
        name: master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi  

  - name: data-zone
    count: 2
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
#            resources:
#              limits:
#                memory: 2Gi
#        initContainers:
#          - name: install-plugins
#            command:
#            - sh
#            - -c
#            - |
#              bin/elasticsearch-plugin install discovery-ec2 

    config:
      node.attr.zone: us-east-1d
      cluster.routing.allocation.awareness.attributes: zone
      node.master: false
      node.data: true
      node.ingest: true

    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
#        storageClassName: gp2


  http:
    service:
      spec:
        type: NodePort

    tls:
      selfSignedCertificate:
        disabled: true



#---
#apiVersion: apm.k8s.elastic.co/v1
#kind: ApmServer
#metadata:
#  name: apm-server
#  namespace: elastic-system
#spec:
#  version: 7.11.1     # was 7.1.0
#  count: 1
#  elasticsearchRef:
#    name: "elasticsearch"
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 7.11.1     # was 7.1.0
  count: 1
  elasticsearchRef:
    name: "elasticsearch"
#    podTemplate:
#      spec:
#        containers:
#          - name: kibana
#            resources:
#              limits:
#                memory: 2Gi

  http:
    service:
      spec:
        type: NodePort
#      	ports:
#	- name: http
#	  port: 80
#	  protocol: TCP
#	  targetPort: 5601
#	- name: https
#	  port: 433
#	  protocol: TCP
#	  targetPort: 5601
        
    tls:
      selfSignedCertificate:
        disabled: true
