apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ha
spec:
  version: 7.5.2
  nodeSets:
  - name: zone-a
    count: 2
    config:
#      node.attr.zone: europe-west1-a
      cluster.routing.allocation.awareness.attributes: zone
      node.master: true
      node.data: false
      node.ingest: false
    volumeClaimTemplates:
    - metadata:
        name: master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp2

    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: zone-b-data
    count: 2
    volumeClaimTemplates:
    - metadata:
        name: zone-b-data-0
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp2

    config:
      node.master: false
      node.data: true
      node.ingest: true
#      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
