apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-external
  namespace: mon
  labels:
    k8s-app: etcd-external-cluster
subsets:
- addresses:
  - ip: 192.168.1.144
 # - ip: 192.168.1.145
 # - ip: 192.168.1.146
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-external
  namespace: mon
  labels:
    k8s-app: etcd-external-cluster
spec:
  selector:
    component: etcd-external
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
    targetPort: 2379
